In [1]:
import pandas as pd
import numpy as np
from scipy import stats

## Z_Score method

In [2]:
data = ({'age':[20,21,22,23,24,25,26,27,28,29,30,50]})
df = pd.DataFrame(data)
df.head(3)

   age
0   20
1   21
2   22

In [3]:
age_mean = np.mean(df['age'])
age_std = np.std(df['age'])   

df['z_score'] = (df['age']-age_mean)/age_std

data = (df[df['z_score'] <= 3])
data

    age   z_score
0    20 -0.938954
1    21 -0.806396
2    22 -0.673838
3    23 -0.541280
4    24 -0.408721
5    25 -0.276163
6    26 -0.143605
7    27 -0.011047
8    28  0.121512
9    29  0.254070
10   30  0.386628

## using z score method

In [4]:
data = ({'values':[2.3,2.4,2.7,2.9,3.0,3.3,3.4,3.6,3.9,4.0,110.9]})
df = pd.DataFrame(data)

z_scor = np.abs(stats.zscore(df))
threshold = 2.5
outlier = np.where(z_scor > threshold)[0]

print(outlier)
for i in outlier:
    print(df.iloc[i]['values'])

[10]
110.9

## Kmean cluster

In [6]:
from sklearn.cluster import KMeans

data = [[2,2],[3,3],[4,5],[30,30],[31,31]]
Kmeans = KMeans(n_clusters = 2, n_init = 10)
Kmeans.fit(data)

labels = Kmeans.predict(data)
print(labels)

outlier = [data[i] for i,label in enumerate(labels) if label == 0]
print(outlier)

[0 0 0 1 1]
[[2, 2], [3, 3], [4, 5]]

## IQR

In [ ]:
data = ({'age' : [23,35,43,55,25,45,50,150]})
df = pd.DataFrame(data)

Q1 = np.percentile(df['age'],25)
Q3 = np.percentile(df['age'],75)

IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

outlier = (df['age'] < lower_bond)|(df['age'] > upper_bond)

clean = df[~outlier]

print(outlier.sum())
print(len(clean))