In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import r2_score, mean_squared_error
from scipy import stats

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
df.drop('deck',axis=1,inplace=True)

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [14]:
z_score = np.abs(stats.zscore(df['fare']))
filter_entries = np.where(z_score < 2.5)[0]
clean_data = df.iloc[filter_entries]


x = clean_data.drop('fare', axis=1)
y = clean_data['fare']

numeric_feature = ['age']
cat_feature = ['sex','sibsp', 'embarked','class','who','adult_male', 'parch','embark_town','alive','alone','survived','pclass',]

models = {
    'linear_model': LinearRegression(),
    'svm': SVR(),
    'neighbors': KNeighborsRegressor(),
    'tree': DecisionTreeRegressor(),
    'ensemble': RandomForestRegressor(),
    'xgboost': XGBRegressor(),
    'catboost': CatBoostRegressor(),
}

num_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='mean')),
    ('scale', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encode', OneHotEncoder()), 
])

preprocessing = ColumnTransformer(transformers=[
    ('num', num_transformer, numeric_feature),
    ('cat', cat_transformer, cat_feature)
])

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

for name, model in models.items():
    
    pipeline = Pipeline(steps=[
        ('preprocessing', preprocessing),
        ('model', model)
    ])

    pipeline.fit(x_train, y_train)
    y_pred = pipeline.predict(x_test)

    print(f"mse of model :{name} is : {mean_squared_error(y_test,y_pred)}")
    print(f"r2 of model {name} is : {r2_score(y_test,y_pred)}")

mse of model :linear_model is : 426.8658822514257
r2 of model linear_model is : 0.599193959678795
mse of model :svm is : 801.7234986234042
r2 of model svm is : 0.2472211196151728
mse of model :neighbors is : 421.41391626914185
r2 of model neighbors is : 0.6043130872272413
mse of model :tree is : 415.4961137112972
r2 of model tree is : 0.6098696123777225
mse of model :ensemble is : 277.4986038650513
r2 of model ensemble is : 0.7394424777562734
mse of model :xgboost is : 322.16166977027984
r2 of model xgboost is : 0.6975060585239305
Learning rate set to 0.037847
0:	learn: 26.0248582	total: 1.42ms	remaining: 1.42s
1:	learn: 25.5334536	total: 2.69ms	remaining: 1.34s
2:	learn: 25.0318738	total: 4.66ms	remaining: 1.55s
3:	learn: 24.4955753	total: 6.54ms	remaining: 1.63s
4:	learn: 24.0200831	total: 8.25ms	remaining: 1.64s
5:	learn: 23.5664196	total: 9.4ms	remaining: 1.56s
6:	learn: 23.1598720	total: 11.3ms	remaining: 1.6s
7:	learn: 22.7119272	total: 13.6ms	remaining: 1.68s
8:	learn: 22.3011065	total: 15.5ms	remaining: 1.71s
9:	learn: 21.9182396	total: 16.5ms	remaining: 1.63s
10:	learn: 21.5746663	total: 18.4ms	remaining: 1.66s
11:	learn: 21.2248508	total: 20.5ms	remaining: 1.69s
12:	learn: 20.9085280	total: 22.5ms	remaining: 1.7s
13:	learn: 20.5706923	total: 24.6ms	remaining: 1.73s
14:	learn: 20.2690353	total: 28ms	remaining: 1.83s
15:	learn: 19.9778596	total: 30.1ms	remaining: 1.85s
16:	learn: 19.7305583	total: 32.1ms	remaining: 1.85s
17:	learn: 19.4590128	total: 34.2ms	remaining: 1.87s
18:	learn: 19.2040747	total: 36.1ms	remaining: 1.86s
19:	learn: 18.9603823	total: 38.1ms	remaining: 1.87s
20:	learn: 18.7402404	total: 40.5ms	remaining: 1.89s
21:	learn: 18.5258512	total: 43.7ms	remaining: 1.94s
22:	learn: 18.2925491	total: 45.7ms	remaining: 1.94s
23:	learn: 18.0887492	total: 47ms	remaining: 1.91s
24:	learn: 17.9369594	total: 47.9ms	remaining: 1.87s
25:	learn: 17.7539187	total: 49.6ms	remaining: 1.86s
26:	learn: 17.5742773	total: 51.7ms	remaining: 1.86s
27:	learn: 17.3930969	total: 53.7ms	remaining: 1.86s
28:	learn: 17.2055681	total: 55.7ms	remaining: 1.86s
29:	learn: 17.0463261	total: 58.4ms	remaining: 1.89s
30:	learn: 16.8869782	total: 60.3ms	remaining: 1.88s
31:	learn: 16.7581123	total: 61.9ms	remaining: 1.87s
32:	learn: 16.6273398	total: 64.1ms	remaining: 1.88s
33:	learn: 16.4851790	total: 66.2ms	remaining: 1.88s
34:	learn: 16.3497968	total: 68.2ms	remaining: 1.88s
35:	learn: 16.2195394	total: 70.4ms	remaining: 1.88s
36:	learn: 16.1162814	total: 73.8ms	remaining: 1.92s
37:	learn: 16.0007299	total: 75.9ms	remaining: 1.92s
38:	learn: 15.8896458	total: 77.9ms	remaining: 1.92s
39:	learn: 15.7981114	total: 80.1ms	remaining: 1.92s
40:	learn: 15.6708638	total: 82.1ms	remaining: 1.92s
41:	learn: 15.5748301	total: 84.1ms	remaining: 1.92s
42:	learn: 15.4778469	total: 86.3ms	remaining: 1.92s
43:	learn: 15.3773194	total: 88.9ms	remaining: 1.93s
44:	learn: 15.2706567	total: 91ms	remaining: 1.93s
45:	learn: 15.2032961	total: 92.9ms	remaining: 1.93s
46:	learn: 15.1124576	total: 94.7ms	remaining: 1.92s
47:	learn: 15.0290673	total: 96.6ms	remaining: 1.92s
48:	learn: 14.9347137	total: 98.4ms	remaining: 1.91s
49:	learn: 14.8739555	total: 101ms	remaining: 1.91s
50:	learn: 14.8075017	total: 103ms	remaining: 1.92s
51:	learn: 14.7380556	total: 105ms	remaining: 1.92s
52:	learn: 14.6829715	total: 107ms	remaining: 1.91s
53:	learn: 14.6188541	total: 109ms	remaining: 1.9s
54:	learn: 14.5425692	total: 111ms	remaining: 1.9s
55:	learn: 14.4907046	total: 113ms	remaining: 1.9s
56:	learn: 14.4320899	total: 115ms	remaining: 1.9s
57:	learn: 14.3804351	total: 117ms	remaining: 1.9s
58:	learn: 14.3395574	total: 119ms	remaining: 1.9s
59:	learn: 14.2962627	total: 121ms	remaining: 1.89s
60:	learn: 14.2419466	total: 123ms	remaining: 1.89s
61:	learn: 14.1767412	total: 125ms	remaining: 1.89s
62:	learn: 14.1029553	total: 127ms	remaining: 1.89s
63:	learn: 14.0613198	total: 129ms	remaining: 1.88s
64:	learn: 14.0167602	total: 131ms	remaining: 1.88s
65:	learn: 13.9679644	total: 133ms	remaining: 1.89s
66:	learn: 13.9021778	total: 135ms	remaining: 1.88s
67:	learn: 13.8307733	total: 137ms	remaining: 1.88s
68:	learn: 13.8027322	total: 139ms	remaining: 1.87s
69:	learn: 13.7780637	total: 140ms	remaining: 1.86s
70:	learn: 13.7345762	total: 142ms	remaining: 1.85s
71:	learn: 13.6942508	total: 144ms	remaining: 1.85s
72:	learn: 13.6410142	total: 146ms	remaining: 1.85s
73:	learn: 13.6097774	total: 148ms	remaining: 1.85s
74:	learn: 13.5797450	total: 149ms	remaining: 1.84s
75:	learn: 13.5367968	total: 151ms	remaining: 1.84s
76:	learn: 13.4785757	total: 153ms	remaining: 1.83s
77:	learn: 13.4255382	total: 155ms	remaining: 1.83s
78:	learn: 13.3851098	total: 157ms	remaining: 1.83s
79:	learn: 13.3653429	total: 159ms	remaining: 1.83s
80:	learn: 13.3251920	total: 161ms	remaining: 1.82s
81:	learn: 13.3000772	total: 163ms	remaining: 1.82s
82:	learn: 13.2702128	total: 165ms	remaining: 1.82s
83:	learn: 13.2421914	total: 167ms	remaining: 1.82s
84:	learn: 13.2205743	total: 169ms	remaining: 1.82s
85:	learn: 13.1889570	total: 171ms	remaining: 1.81s
86:	learn: 13.1828975	total: 172ms	remaining: 1.8s
87:	learn: 13.1612873	total: 173ms	remaining: 1.8s
88:	learn: 13.1422074	total: 176ms	remaining: 1.8s
89:	learn: 13.1267528	total: 178ms	remaining: 1.79s
90:	learn: 13.1200407	total: 179ms	remaining: 1.78s
91:	learn: 13.1040066	total: 181ms	remaining: 1.78s
92:	learn: 13.0750650	total: 182ms	remaining: 1.78s
93:	learn: 13.0562725	total: 184ms	remaining: 1.78s
94:	learn: 13.0166260	total: 186ms	remaining: 1.77s
95:	learn: 12.9946025	total: 188ms	remaining: 1.77s
96:	learn: 12.9701243	total: 190ms	remaining: 1.77s
97:	learn: 12.9299028	total: 193ms	remaining: 1.77s
98:	learn: 12.9147023	total: 195ms	remaining: 1.77s
99:	learn: 12.9016355	total: 196ms	remaining: 1.76s
100:	learn: 12.8887071	total: 198ms	remaining: 1.76s
101:	learn: 12.8659120	total: 200ms	remaining: 1.76s
102:	learn: 12.8417691	total: 202ms	remaining: 1.76s
103:	learn: 12.8197170	total: 204ms	remaining: 1.76s
104:	learn: 12.8094553	total: 206ms	remaining: 1.75s
105:	learn: 12.7887589	total: 209ms	remaining: 1.77s
106:	learn: 12.7607185	total: 212ms	remaining: 1.76s
107:	learn: 12.7560319	total: 213ms	remaining: 1.76s
108:	learn: 12.7256719	total: 215ms	remaining: 1.76s
109:	learn: 12.7055005	total: 217ms	remaining: 1.76s
110:	learn: 12.6897012	total: 219ms	remaining: 1.75s
111:	learn: 12.6763990	total: 221ms	remaining: 1.75s
112:	learn: 12.6590358	total: 224ms	remaining: 1.76s
113:	learn: 12.6555088	total: 225ms	remaining: 1.75s
114:	learn: 12.6143146	total: 227ms	remaining: 1.75s
115:	learn: 12.5954062	total: 229ms	remaining: 1.74s
116:	learn: 12.5820858	total: 230ms	remaining: 1.74s
117:	learn: 12.5791914	total: 231ms	remaining: 1.73s
118:	learn: 12.5638359	total: 233ms	remaining: 1.73s
119:	learn: 12.5369549	total: 235ms	remaining: 1.72s
120:	learn: 12.5111864	total: 238ms	remaining: 1.73s
121:	learn: 12.4772710	total: 240ms	remaining: 1.73s
122:	learn: 12.4387995	total: 243ms	remaining: 1.73s
123:	learn: 12.4195232	total: 245ms	remaining: 1.73s
124:	learn: 12.4091072	total: 247ms	remaining: 1.73s
125:	learn: 12.3698391	total: 248ms	remaining: 1.72s
126:	learn: 12.3655198	total: 250ms	remaining: 1.72s
127:	learn: 12.3459395	total: 252ms	remaining: 1.71s
128:	learn: 12.3329999	total: 254ms	remaining: 1.71s
129:	learn: 12.3113027	total: 256ms	remaining: 1.71s
130:	learn: 12.3025493	total: 257ms	remaining: 1.71s
131:	learn: 12.2903054	total: 259ms	remaining: 1.7s
132:	learn: 12.2771439	total: 261ms	remaining: 1.7s
133:	learn: 12.2617807	total: 263ms	remaining: 1.7s
134:	learn: 12.2448909	total: 265ms	remaining: 1.7s
135:	learn: 12.2264827	total: 268ms	remaining: 1.7s
136:	learn: 12.2173941	total: 270ms	remaining: 1.7s
137:	learn: 12.2071578	total: 272ms	remaining: 1.7s
138:	learn: 12.2003933	total: 274ms	remaining: 1.7s
139:	learn: 12.1890154	total: 276ms	remaining: 1.69s
140:	learn: 12.1670449	total: 278ms	remaining: 1.69s
141:	learn: 12.1520057	total: 279ms	remaining: 1.69s
142:	learn: 12.1444146	total: 281ms	remaining: 1.69s
143:	learn: 12.1377434	total: 283ms	remaining: 1.68s
144:	learn: 12.1313311	total: 286ms	remaining: 1.68s
145:	learn: 12.1134371	total: 288ms	remaining: 1.68s
146:	learn: 12.1095684	total: 289ms	remaining: 1.68s
147:	learn: 12.0991195	total: 291ms	remaining: 1.67s
148:	learn: 12.0931007	total: 293ms	remaining: 1.67s
149:	learn: 12.0816492	total: 295ms	remaining: 1.67s
150:	learn: 12.0760696	total: 297ms	remaining: 1.67s
151:	learn: 12.0598123	total: 299ms	remaining: 1.67s
152:	learn: 12.0541410	total: 301ms	remaining: 1.66s
153:	learn: 12.0474030	total: 303ms	remaining: 1.66s
154:	learn: 12.0437259	total: 304ms	remaining: 1.66s
155:	learn: 12.0255703	total: 307ms	remaining: 1.66s
156:	learn: 12.0068441	total: 308ms	remaining: 1.66s
157:	learn: 11.9986443	total: 310ms	remaining: 1.65s
158:	learn: 11.9809814	total: 312ms	remaining: 1.65s
159:	learn: 11.9591333	total: 314ms	remaining: 1.65s
160:	learn: 11.9567101	total: 316ms	remaining: 1.65s
161:	learn: 11.9374121	total: 318ms	remaining: 1.64s
162:	learn: 11.9215791	total: 320ms	remaining: 1.64s
163:	learn: 11.9177869	total: 322ms	remaining: 1.64s
164:	learn: 11.9124370	total: 324ms	remaining: 1.64s
165:	learn: 11.8921490	total: 326ms	remaining: 1.64s
166:	learn: 11.8879457	total: 328ms	remaining: 1.64s
167:	learn: 11.8714133	total: 331ms	remaining: 1.64s
168:	learn: 11.8547609	total: 332ms	remaining: 1.63s
169:	learn: 11.8481341	total: 334ms	remaining: 1.63s
170:	learn: 11.8422433	total: 336ms	remaining: 1.63s
171:	learn: 11.8372609	total: 338ms	remaining: 1.63s
172:	learn: 11.8332961	total: 340ms	remaining: 1.63s
173:	learn: 11.8082649	total: 342ms	remaining: 1.62s
174:	learn: 11.7978847	total: 344ms	remaining: 1.62s
175:	learn: 11.7894431	total: 346ms	remaining: 1.62s
176:	learn: 11.7851982	total: 348ms	remaining: 1.62s
177:	learn: 11.7840720	total: 350ms	remaining: 1.61s
178:	learn: 11.7763951	total: 352ms	remaining: 1.61s
179:	learn: 11.7740776	total: 354ms	remaining: 1.61s
180:	learn: 11.7625400	total: 356ms	remaining: 1.61s
181:	learn: 11.7596594	total: 358ms	remaining: 1.61s
182:	learn: 11.7519451	total: 360ms	remaining: 1.61s
183:	learn: 11.7486265	total: 363ms	remaining: 1.61s
184:	learn: 11.7436413	total: 365ms	remaining: 1.61s
185:	learn: 11.7360196	total: 367ms	remaining: 1.61s
186:	learn: 11.7315588	total: 369ms	remaining: 1.6s
187:	learn: 11.7166528	total: 371ms	remaining: 1.6s
188:	learn: 11.7042289	total: 374ms	remaining: 1.6s
189:	learn: 11.6998886	total: 375ms	remaining: 1.6s
190:	learn: 11.6941324	total: 377ms	remaining: 1.59s
191:	learn: 11.6882500	total: 379ms	remaining: 1.59s
192:	learn: 11.6809730	total: 381ms	remaining: 1.59s
193:	learn: 11.6748856	total: 383ms	remaining: 1.59s
194:	learn: 11.6672118	total: 385ms	remaining: 1.59s
195:	learn: 11.6536353	total: 388ms	remaining: 1.59s
196:	learn: 11.6450351	total: 390ms	remaining: 1.59s
197:	learn: 11.6306888	total: 392ms	remaining: 1.59s
198:	learn: 11.6259850	total: 394ms	remaining: 1.59s
199:	learn: 11.6213289	total: 396ms	remaining: 1.58s
200:	learn: 11.6184358	total: 398ms	remaining: 1.58s
201:	learn: 11.6111099	total: 400ms	remaining: 1.58s
202:	learn: 11.5966948	total: 403ms	remaining: 1.58s
203:	learn: 11.5812681	total: 406ms	remaining: 1.58s
204:	learn: 11.5760640	total: 408ms	remaining: 1.58s
205:	learn: 11.5695164	total: 411ms	remaining: 1.58s
206:	learn: 11.5659045	total: 412ms	remaining: 1.58s
207:	learn: 11.5616236	total: 415ms	remaining: 1.58s
208:	learn: 11.5577555	total: 417ms	remaining: 1.58s
209:	learn: 11.5436504	total: 420ms	remaining: 1.58s
210:	learn: 11.5256899	total: 422ms	remaining: 1.58s
211:	learn: 11.5227427	total: 424ms	remaining: 1.58s
212:	learn: 11.5161284	total: 426ms	remaining: 1.57s
213:	learn: 11.5144572	total: 428ms	remaining: 1.57s
214:	learn: 11.5028402	total: 430ms	remaining: 1.57s
215:	learn: 11.4852914	total: 432ms	remaining: 1.57s
216:	learn: 11.4805187	total: 435ms	remaining: 1.57s
217:	learn: 11.4756427	total: 436ms	remaining: 1.56s
218:	learn: 11.4720700	total: 439ms	remaining: 1.56s
219:	learn: 11.4646547	total: 441ms	remaining: 1.56s
220:	learn: 11.4595109	total: 443ms	remaining: 1.56s
221:	learn: 11.4541140	total: 445ms	remaining: 1.56s
222:	learn: 11.4416425	total: 448ms	remaining: 1.56s
223:	learn: 11.4378833	total: 451ms	remaining: 1.56s
224:	learn: 11.4314352	total: 453ms	remaining: 1.56s
225:	learn: 11.4245226	total: 455ms	remaining: 1.56s
226:	learn: 11.4050288	total: 457ms	remaining: 1.55s
227:	learn: 11.3958941	total: 459ms	remaining: 1.55s
228:	learn: 11.3941422	total: 460ms	remaining: 1.55s
229:	learn: 11.3918814	total: 464ms	remaining: 1.55s
230:	learn: 11.3890735	total: 466ms	remaining: 1.55s
231:	learn: 11.3781607	total: 468ms	remaining: 1.55s
232:	learn: 11.3751943	total: 470ms	remaining: 1.55s
233:	learn: 11.3734005	total: 472ms	remaining: 1.54s
234:	learn: 11.3702593	total: 474ms	remaining: 1.54s
235:	learn: 11.3671749	total: 476ms	remaining: 1.54s
236:	learn: 11.3617989	total: 479ms	remaining: 1.54s
237:	learn: 11.3589871	total: 481ms	remaining: 1.54s
238:	learn: 11.3490952	total: 483ms	remaining: 1.54s
239:	learn: 11.3474127	total: 485ms	remaining: 1.54s
240:	learn: 11.3408497	total: 487ms	remaining: 1.53s
241:	learn: 11.3392498	total: 489ms	remaining: 1.53s
242:	learn: 11.3365573	total: 491ms	remaining: 1.53s
243:	learn: 11.3350496	total: 494ms	remaining: 1.53s
244:	learn: 11.3338914	total: 497ms	remaining: 1.53s
245:	learn: 11.3324871	total: 499ms	remaining: 1.53s
246:	learn: 11.3313214	total: 501ms	remaining: 1.53s
247:	learn: 11.3297635	total: 503ms	remaining: 1.52s
248:	learn: 11.3280550	total: 506ms	remaining: 1.53s
249:	learn: 11.3258202	total: 510ms	remaining: 1.53s
250:	learn: 11.3232629	total: 512ms	remaining: 1.53s
251:	learn: 11.3212097	total: 515ms	remaining: 1.53s
252:	learn: 11.3058980	total: 517ms	remaining: 1.53s
253:	learn: 11.3036738	total: 519ms	remaining: 1.52s
254:	learn: 11.3016038	total: 521ms	remaining: 1.52s
255:	learn: 11.3004135	total: 523ms	remaining: 1.52s
256:	learn: 11.2914732	total: 525ms	remaining: 1.52s
257:	learn: 11.2903203	total: 527ms	remaining: 1.52s
258:	learn: 11.2891882	total: 529ms	remaining: 1.51s
259:	learn: 11.2872338	total: 531ms	remaining: 1.51s
260:	learn: 11.2853558	total: 533ms	remaining: 1.51s
261:	learn: 11.2772776	total: 535ms	remaining: 1.51s
262:	learn: 11.2749486	total: 538ms	remaining: 1.51s
263:	learn: 11.2702818	total: 540ms	remaining: 1.51s
264:	learn: 11.2692690	total: 543ms	remaining: 1.51s
265:	learn: 11.2669999	total: 545ms	remaining: 1.5s
266:	learn: 11.2658336	total: 547ms	remaining: 1.5s
267:	learn: 11.2642312	total: 548ms	remaining: 1.5s
268:	learn: 11.2604606	total: 550ms	remaining: 1.49s
269:	learn: 11.2563926	total: 553ms	remaining: 1.49s
270:	learn: 11.2449427	total: 554ms	remaining: 1.49s
271:	learn: 11.2436375	total: 556ms	remaining: 1.49s
272:	learn: 11.2414590	total: 558ms	remaining: 1.49s
273:	learn: 11.2298150	total: 561ms	remaining: 1.49s
274:	learn: 11.2276873	total: 563ms	remaining: 1.48s
275:	learn: 11.2243136	total: 564ms	remaining: 1.48s
276:	learn: 11.2222194	total: 566ms	remaining: 1.48s
277:	learn: 11.2166432	total: 569ms	remaining: 1.48s
278:	learn: 11.2157774	total: 572ms	remaining: 1.48s
279:	learn: 11.2140206	total: 573ms	remaining: 1.47s
280:	learn: 11.2099795	total: 575ms	remaining: 1.47s
281:	learn: 11.2059586	total: 577ms	remaining: 1.47s
282:	learn: 11.2050965	total: 579ms	remaining: 1.47s
283:	learn: 11.2007226	total: 581ms	remaining: 1.47s
284:	learn: 11.1954149	total: 601ms	remaining: 1.51s
285:	learn: 11.1863489	total: 604ms	remaining: 1.51s
286:	learn: 11.1846911	total: 606ms	remaining: 1.5s
287:	learn: 11.1760627	total: 608ms	remaining: 1.5s
288:	learn: 11.1704381	total: 610ms	remaining: 1.5s
289:	learn: 11.1660764	total: 611ms	remaining: 1.5s
290:	learn: 11.1645018	total: 613ms	remaining: 1.49s
291:	learn: 11.1486319	total: 631ms	remaining: 1.53s
292:	learn: 11.1474178	total: 634ms	remaining: 1.53s
293:	learn: 11.1455106	total: 637ms	remaining: 1.53s
294:	learn: 11.1397436	total: 639ms	remaining: 1.53s
295:	learn: 11.1304615	total: 641ms	remaining: 1.52s
296:	learn: 11.1108156	total: 643ms	remaining: 1.52s
297:	learn: 11.0996273	total: 645ms	remaining: 1.52s
298:	learn: 11.0809898	total: 648ms	remaining: 1.52s
299:	learn: 11.0794269	total: 650ms	remaining: 1.51s
300:	learn: 11.0786127	total: 651ms	remaining: 1.51s
301:	learn: 11.0637061	total: 653ms	remaining: 1.51s
302:	learn: 11.0616286	total: 656ms	remaining: 1.51s
303:	learn: 11.0439841	total: 657ms	remaining: 1.5s
304:	learn: 11.0356367	total: 659ms	remaining: 1.5s
305:	learn: 11.0251709	total: 662ms	remaining: 1.5s
306:	learn: 11.0164658	total: 664ms	remaining: 1.5s
307:	learn: 11.0157462	total: 667ms	remaining: 1.5s
308:	learn: 11.0095965	total: 669ms	remaining: 1.5s
309:	learn: 11.0081936	total: 671ms	remaining: 1.49s
310:	learn: 10.9911780	total: 673ms	remaining: 1.49s
311:	learn: 10.9851012	total: 674ms	remaining: 1.49s
312:	learn: 10.9790359	total: 677ms	remaining: 1.49s
313:	learn: 10.9731207	total: 680ms	remaining: 1.48s
314:	learn: 10.9726413	total: 682ms	remaining: 1.48s
315:	learn: 10.9677238	total: 684ms	remaining: 1.48s
316:	learn: 10.9550452	total: 686ms	remaining: 1.48s
317:	learn: 10.9510093	total: 688ms	remaining: 1.48s
318:	learn: 10.9497156	total: 690ms	remaining: 1.47s
319:	learn: 10.9484029	total: 693ms	remaining: 1.47s
320:	learn: 10.9445131	total: 695ms	remaining: 1.47s
321:	learn: 10.9433031	total: 697ms	remaining: 1.47s
322:	learn: 10.9420782	total: 699ms	remaining: 1.47s
323:	learn: 10.9403275	total: 701ms	remaining: 1.46s
324:	learn: 10.9329749	total: 703ms	remaining: 1.46s
325:	learn: 10.9274064	total: 705ms	remaining: 1.46s
326:	learn: 10.9220834	total: 708ms	remaining: 1.46s
327:	learn: 10.9119406	total: 710ms	remaining: 1.45s
328:	learn: 10.9111483	total: 713ms	remaining: 1.45s
329:	learn: 10.9024924	total: 715ms	remaining: 1.45s
330:	learn: 10.8985553	total: 716ms	remaining: 1.45s
331:	learn: 10.8979152	total: 718ms	remaining: 1.45s
332:	learn: 10.8905869	total: 720ms	remaining: 1.44s
333:	learn: 10.8829786	total: 724ms	remaining: 1.44s
334:	learn: 10.8792848	total: 726ms	remaining: 1.44s
335:	learn: 10.8690188	total: 728ms	remaining: 1.44s
336:	learn: 10.8679111	total: 731ms	remaining: 1.44s
337:	learn: 10.8611031	total: 733ms	remaining: 1.44s
338:	learn: 10.8545453	total: 735ms	remaining: 1.43s
339:	learn: 10.8447407	total: 737ms	remaining: 1.43s
340:	learn: 10.8315365	total: 739ms	remaining: 1.43s
341:	learn: 10.8212351	total: 741ms	remaining: 1.43s
342:	learn: 10.8058056	total: 743ms	remaining: 1.42s
343:	learn: 10.8007228	total: 745ms	remaining: 1.42s
344:	learn: 10.7955779	total: 747ms	remaining: 1.42s
345:	learn: 10.7893640	total: 749ms	remaining: 1.42s
346:	learn: 10.7833770	total: 752ms	remaining: 1.41s
347:	learn: 10.7647499	total: 754ms	remaining: 1.41s
348:	learn: 10.7597158	total: 756ms	remaining: 1.41s
349:	learn: 10.7574880	total: 757ms	remaining: 1.41s
350:	learn: 10.7490041	total: 759ms	remaining: 1.4s
351:	learn: 10.7441101	total: 761ms	remaining: 1.4s
352:	learn: 10.7369137	total: 762ms	remaining: 1.4s
353:	learn: 10.7310106	total: 764ms	remaining: 1.39s
354:	learn: 10.7163127	total: 767ms	remaining: 1.39s
355:	learn: 10.7068108	total: 769ms	remaining: 1.39s
356:	learn: 10.6942508	total: 771ms	remaining: 1.39s
357:	learn: 10.6831199	total: 772ms	remaining: 1.39s
358:	learn: 10.6762136	total: 774ms	remaining: 1.38s
359:	learn: 10.6621436	total: 776ms	remaining: 1.38s
360:	learn: 10.6609963	total: 777ms	remaining: 1.38s
361:	learn: 10.6365513	total: 779ms	remaining: 1.37s
362:	learn: 10.6299454	total: 781ms	remaining: 1.37s
363:	learn: 10.6235281	total: 783ms	remaining: 1.37s
364:	learn: 10.6173216	total: 785ms	remaining: 1.36s
365:	learn: 10.6145985	total: 787ms	remaining: 1.36s
366:	learn: 10.6132139	total: 789ms	remaining: 1.36s
367:	learn: 10.6071625	total: 791ms	remaining: 1.36s